from . import account_move
from . import account_move_line
from . import res_config_settings
from . import account_account_type
from . import account_financial_report
from . import account_asset
from . import product
from . import account_budget
from . import account_analytic_account
from . import account_fiscal_year
from . import res_company
from . import recurring_template
from . import recurring_payment
from . import followup
from . import followup_partner
from . import partner
